apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress
namespace: ingress-nginx
spec:
  replicas: 2
  selector:
    app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
      - name: nginx-ingress
        image: nginx:1.21.0
        ports:
        - containerPort: 80
        - containerPort: 443
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-termination: "ON"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
namespace: ingress-nginx
spec:
  selector:
    app: nginx-ingress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer

  ---
  apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
namespace: default
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app
                port:
                  number: 80