apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
  nodeSelector:
    kubernetes.io/hostname: <cordoned-node-name>  # Replace with the actual node name
