apiVersion: v1
kind: Service
metadata:
  name: mongodb-load-balancer
  labels:
    app: mongodb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb
